//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class PRO_PRO_PRODUTO
    {
        [Key]
        public int PRO_N_CODIGO { get; set; }

        [Required(ErrorMessage = "Referência é obrigatório.")]
        public string PRO_N_REFERENCIA { get; set; }

        [Required(ErrorMessage = "Nome é obrigatório.")]
        public string PRO_C_NOME { get; set; }

        [Required(ErrorMessage = "Descrição é obrigatório.")]
        public string PRO_C_DESCRICAO { get; set; }

        [Required(ErrorMessage = "Marca é obrigatório.")]
        public string PRO_C_MARCA { get; set; }

        [Required(ErrorMessage = "Cor é obrigatório.")]
        public string PRO_C_COR { get; set; }

        [Required(ErrorMessage = "Valor é obrigatório.")]
        public Nullable<decimal> PRO_C_VALOR { get; set; }

        public Nullable<decimal> PRO_C_VALOR_VENDA { get; set; }

        [Required(ErrorMessage = "Quantidade é obrigatório.")]
        public Nullable<decimal> PRO_C_PORCENTAGEM { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PRO_D_DATA_CADASTRO { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PRO_D_DATA_VENDA { get; set; }

        [Required(ErrorMessage = "Tamanho é obrigatório.")]
        public string PRO_C_TAMANHO { get; set; }
        [Required(ErrorMessage = "Situação é obrigatório.")]
        public Nullable<int> PRO_N_SITUACAO { get; set; }

        public string PRO_C_IMAGEM { get; set; }
        public Nullable<bool> PRO_B_ATIVO { get; set; }
    }
}
