//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class PRO_USU_USUARIO
    {
        [Key]
        public int USU_N_CODIGO { get; set; }

        [Required(ErrorMessage = "Nome do usuário é obrigatório.")]
        public string USU_C_NOME { get; set; }

        [Required(ErrorMessage = "Senha é obrigatório.")]
        public string USU_C_SENHA { get; set; }

        public Nullable<bool> USU_C_ATIVO { get; set; }
    }
}
