//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Produtos : DbContext
    {
        public Produtos()
            : base("name=Produtos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRO_PRO_PRODUTO> PRO_PRO_PRODUTO { get; set; }
        public virtual DbSet<PRO_USU_USUARIO> PRO_USU_USUARIO { get; set; }
    
        public virtual int PRO_I_IMAGEM(string pRO_C_IMAGEM, Nullable<int> pRO_N_CODIGO)
        {
            var pRO_C_IMAGEMParameter = pRO_C_IMAGEM != null ?
                new ObjectParameter("PRO_C_IMAGEM", pRO_C_IMAGEM) :
                new ObjectParameter("PRO_C_IMAGEM", typeof(string));
    
            var pRO_N_CODIGOParameter = pRO_N_CODIGO.HasValue ?
                new ObjectParameter("PRO_N_CODIGO", pRO_N_CODIGO) :
                new ObjectParameter("PRO_N_CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRO_I_IMAGEM", pRO_C_IMAGEMParameter, pRO_N_CODIGOParameter);
        }
    
        public virtual ObjectResult<Business.PRO_L_SACOLA_Result> PRO_L_SACOLA(string pRO_N_REFERENCIA)
        {
            var pRO_N_REFERENCIAParameter = pRO_N_REFERENCIA != null ?
                new ObjectParameter("PRO_N_REFERENCIA", pRO_N_REFERENCIA) :
                new ObjectParameter("PRO_N_REFERENCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Business.PRO_L_SACOLA_Result>("PRO_L_SACOLA", pRO_N_REFERENCIAParameter);
        }
    }
}
